import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
} from 'typeorm';

// AttemptEntity
//
// Stores a single answer attempt by a user.
//
// Auth notes (post-MVP):
// - Supports both authenticated (GitHub OAuth) and anonymous users.
// - userId: Always contains a stable identifier.
//   - For authenticated users: UUID of the user record (optional link)
//   - For anonymous users: UUID generated by the frontend
// - authType: Indicates how this attempt was made.
// - githubUserId: Optional link to the users table for authenticated attempts.
//
// Backward compatibility:
// - Old attempts with only userId continue to work (treated as anonymous).

export type AttemptMode = 'daily' | 'exam';
export type AuthType = 'anonymous' | 'github';

@Entity({ name: 'attempts' })
export class AttemptEntity {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  // Stable user identifier (UUID format)
  // - For anonymous: frontend-generated UUID
  // - For authenticated: can be linked to users table via githubUserId
  @Index()
  @Column({ type: 'text' })
  userId!: string;

  @Index()
  @Column({ type: 'text' })
  questionId!: string;

  @Column({ type: 'text' })
  mode!: AttemptMode;

  // Selected answer (e.g. "A").
  @Column({ type: 'text' })
  selectedChoice!: string;

  // Whether the selected choice matched the correct answer at the time.
  @Column({ type: 'boolean' })
  isCorrect!: boolean;

  // Authentication type for this attempt
  // - 'anonymous': legacy and new anonymous attempts
  // - 'github': authenticated via GitHub OAuth
  @Index()
  @Column({ name: 'auth_type', type: 'varchar', length: 20, default: 'anonymous' })
  authType!: AuthType;

  // Optional reference to the users table (for authenticated attempts)
  // NULL for anonymous attempts (backward compatible)
  @Index()
  @Column({ name: 'github_user_id', type: 'text', nullable: true })
  githubUserId!: string | null;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt!: Date;
}
