-- Migration: Seed chapters with manga story content
-- Created: 2024-02-11

-- Insert chapters from the manga story
INSERT INTO chapters (number, title, content, concept_keys, "order", type) VALUES
(0, 'Prologue : Bienvenue au Cloud', 
E'**AWS. Amazon Web Services.**\n\n'
'Imagine une entreprise géante qui possède des millions d''ordinateurs dans des hangars immenses à travers le monde. Au lieu d''acheter ton propre ordinateur cher et limité, tu peux louer une partie de ces machines... via Internet. C''est ça, le **Cloud**.\n\n'
'**Et le meilleur dans tout ça ?** Pour les étudiants et les petits projets, AWS offre un **Free Tier** — un niveau gratuit qui permet d''expérimenter sans payer.\n\n'
'---\n\n'
'Yuki, 16 ans, regardait son écran d''ordinateur avec détermination. Dans trois semaines, le lycée Kumo organiserait son festival annuel — trois jours de stands, de concerts et de compétitions. Et elle avait promis de créer une application pour gérer les inscriptions.\n\n'
'"C''est mission impossible," avait dit Kenji, le président du comité. "Tu es seule, et tu n''as pas de serveur."\n\n'
'Mais Yuki avait découvert quelque chose. Une porte d''entrée vers un monde où les ordinateurs ne coûtent que quand on les utilise.\n\n'
'Elle ouvrit son navigateur et tapa trois lettres : **A-W-S**.\n\n'
'"D''accord," murmura-t-elle. "Commençons."',
ARRAY['aws_cloud', 'free_tier'], 0, 'prologue'),

(1, 'Chapitre 1 : Le Robot Cuisinier 🍜', 
E'Le premier problème de Yuki était simple : comment faire fonctionner son application sans avoir d''ordinateur allumé 24h/24 ?\n\n'
'Elle découvrit alors le **Robot Cuisinier (Lambda)**. Imagine un chef robot qui dort dans sa cuisine jusqu''à ce que quelqu''un sonne. Dès qu''une commande arrive, il se réveille, prépare le plat en quelques secondes, puis retourne dormir.\n\n'
'"C''est exactement ce qu''il me faut !" s''exclama Yuki.\n\n'
'Elle créa son premier robot. Le code était simple : quand quelqu''un remplissait le formulaire, le robot enregistrait l''inscription. Elle testa avec ses propres informations.\n\n'
'**ERREUR.**\n\n'
'Le robot avait planté. Yuki avait oublié de vérifier si l''email était valide. Elle corrigea le code, ajouta une vérification, et retenta.\n\n'
'**ÇA MARCHE !**\n\n'
'Mais un problème surgit : comment empêcher n''importe qui d''utiliser son robot ? Elle découvrit les **Badges d''Accès (IAM)** :\n'
'- **Badge Vert** : Peut uniquement consulter\n'
'- **Badge Orange** : Peut s''inscrire\n'
'- **Badge Rouge** : Peut tout modifier\n\n'
'Yuki créa son système de Badges. Elle réalisa qu''elle venait de construire une **Porte d''Entrée (API Gateway)** — comme l''entrée du lycée avec un gardien qui vérifiait les badges.\n\n'
'"C''est comme quand je commande sur Uber Eats," se dit-elle. "L''appli est une interface entre moi et le restaurant."\n\n'
'Elle testa. L''inscription fonctionna. Elle testa avec un Badge Vert en essayant de modifier... **ACCÈS REFUSÉ**.\n\n'
'Mais alors qu''elle célébrait, elle regarda son vieux disque dur : 98% plein.\n\n'
'"Il me faut un casier plus grand."',
ARRAY['lambda_execution', 'iam_roles', 'least_privilege', 'api_gateway'], 1, 'chapter'),

(2, 'Chapitre 2 : Le Casier Scolaire Infini 🗄️', 
E'Yuki contemplait son écran. Les premiers testeurs avaient uploadé des photos de leurs stands, et son ordinateur explosait. Et pire : Kenji lui avait envoyé un message : "J''ai montré l''appli au proviseur. Il veut une démo dans 48 heures."\n\n'
'**48 heures.**\n\n'
'Yuki découvrit le **Casier Scolaire Infini (S3)**. Ici, tu peux stocker TOUT. Photos, vidéos... L''espace est pratiquement illimité.\n\n'
'Elle uploada une photo de test. Le système lui retourna une clé unique : `stands/musique/affiche.jpg`\n\n'
'"C''est quoi cette clé étrange ?"\n\n'
'"C''est l''adresse exacte de ton fichier. Comme le numéro d''un casier scolaire."\n\n'
'Mais les inscriptions elles-mêmes — les noms, les emails — étaient différentes. Ce n''étaient pas des fichiers, mais des **données structurées**.\n\n'
'Yuki découvrit alors les **Fiches Élèves Magiques (DynamoDB)**. Des millions de fiches cartonnées, chacune avec un numéro unique. Quand elle cherchait "Inscription #2847", le système trouvait instantanément.\n\n'
'"Et si je veux chercher toutes les inscriptions pour le stand de musique ?"\n\n'
'"Tu crées un **index secondaire**. Comme un annuaire inversé."\n\n'
'Yuki travailla toute la nuit. À 3h du matin, tout fonctionnait. Les photos dans le Casier Infini, les données dans les Fiches Magiques.\n\n'
'Mais alors qu''elle allait fermer son ordinateur, deux notifications apparurent :\n\n'
'"ALERTE : Tentative d''accès non autorisée détectée."\n\n'
'Et un message privé sur son téléphone, d''un numéro inconnu :\n\n'
'"Belle appli. Dommage que ce soit si facile à pirater. — K"',
ARRAY['s3_buckets', 's3_keys', 'dynamodb_keys', 'dynamodb_indexes'], 2, 'chapter'),

(3, 'Chapitre 3 : Le Piège du Hacker 🎭', 
E'Yuki paniqua. Son écran affichait des lignes de code défilant. Quelqu''un avait trouvé l''URL de son application et essayait de forcer l''entrée.\n\n'
'Elle regarda son code. Horreur. Elle avait écrit la clé d''accès aux Fiches Élèves Magiques directement dans le programme.\n\n'
'"Stupide !" s''écria-t-elle.\n\n'
'Elle chercha frénétiquement une solution. C''est alors qu''elle découvrit le **Coffre-Fort Numérique (Secrets Manager)**.\n\n'
'"C''est comme un coffre-fort dans ta chambre. Au lieu de laisser ton argent traîner sur la table, tu le mets dans le coffre."\n\n'
'Yuki créa son Coffre-Fort en urgence. Elle y déposa la clé d''accès, le mot de passe administrateur, et la **clé API** pour envoyer des emails.\n\n'
'"C''est quoi une clé API ?"\n\n'
'"C''est comme une carte d''identité pour que deux applications parlent entre elles."\n\n'
'Elle modifia son code. Plus aucune clé sensible n''apparaissait. Elle regarda les logs du Coffre-Fort. Trois tentatives d''accès avaient été bloquées.\n\n'
'"Bloqué," sourit-elle.\n\n'
'Mais son téléphone vibra. Nouveau message du numéro inconnu :\n\n'
'"Tu as été rapide. Mais le festival approche... On se reverra. — K"\n\n'
'Yuki frissonna. Ce "K" n''avait pas lâché l''affaire.\n\n'
'Au réveil, elle découvrit 50 nouvelles inscriptions... et aucune notification envoyée aux organisateurs. Les présidents de stands ne savaient même pas qu''ils avaient des candidats.\n\n'
'"Il me faut un système de messagerie."',
ARRAY['secrets_manager', 'api_keys', 'credentials'], 3, 'chapter'),

(4, 'Chapitre 4 : Les Messagers du Lycée 📬', 
E'Yuki devait trouver un moyen de connecter son Robot Cuisinier aux présidents de stands.\n\n'
'Elle découvrit alors les deux Messagers du Lycée.\n\n'
'**La Boîte aux Lettres (SQS)** : Ton robot dépose un message. Le président du stand passe quand il veut, ouvre la boîte, récupère le message. Un seul destinataire.\n\n'
'**Le Haut-Parleur (SNS)** : Ton robot annonce : "Concert ce soir à 18h !" TOUT LE MONDE entend en même temps.\n\n'
'Yuki réfléchit. Pour les inscriptions spécifiques à un stand, elle utiliserait la **Boîte aux Lettres**. Pour les annonces générales, le **Haut-Parleur**.\n\n'
'Elle configura son système. Test. Échec. Elle avait oublié de lier le Haut-Parleur aux numéros de téléphone. Elle corrigea, retenta.\n\n'
'**Notification reçue !** Le président du stand de musique venait de recevoir un SMS.\n\n'
'Elle montra à Kenji. Il testa avec son téléphone... et planta.\n\n'
'"ERREUR 502 - Service Indisponible"\n\n'
'Trois cents élèves venaient d''essayer de s''inscrire suite à l''annonce de Kenji. L''application venait de s''effondrer.\n\n'
'"Le festival est dans trois jours," dit Kenji, blême. "Je suis désolé, j''aurais pas dû annoncer sans te demander."\n\n'
'Yuki le regarda. Pour la première fois, il reconnaissait avoir fait une erreur.\n\n'
'"On va réparer ensemble," dit-elle."',
ARRAY['sqs_queue', 'sqs_dlq', 'sns_topic'], 4, 'chapter'),

(5, 'Chapitre 5 : L''Armée des Robots 🎖️', 
E'La nuit suivant le crash, Yuki et Kenji étaient devant l''écran. Yuki avait expliqué le problème : un seul Robot Cuisinier ne pouvait pas gérer 300 requêtes simultanées.\n\n'
'"Il nous faut une armée," dit Yuki.\n\n'
'Elle découvrit l''**Auto-Scaling**. Quand il y a trop de monde, le Robot Cuisinier se multiplie automatiquement.\n\n'
'"Imagine une armée de robots identiques. Quand il y a peu de monde, un seul suffit. Quand la cantine est bondée, dix robots se mettent au travail."\n\n'
'"Et ça coûte cher ?" demanda Kenji.\n\n'
'"Avec le Free Tier, les premiers milliers de requêtes sont gratuites."\n\n'
'Yuki configura les alertes. Si plus de 50 personnes étaient connectées, l''Auto-Scaling déclencherait de nouveaux robots.\n\n'
'Soudain, son téléphone vibra. Message de "K" :\n\n'
'"Tu as résolu le problème de charge ? Impressionnant. Mais regardons si ton système tient contre ça..."\n\n'
'Une seconde plus tard, le **Tableau de Bord du Proviseur (CloudWatch)** afficha une alerte rouge : quelqu''un essayait de saturer l''application avec des milliers de requêtes fausses.\n\n'
'"C''est une attaque DDOS !" s''écria Yuki.\n\n'
'Mais cette fois, elle était prête. L''**Armée des Robots** se déploya automatiquement. Un robot, puis deux, puis dix. L''application absorba l''attaque sans ralentir.\n\n'
'"Bloqué," sourit Yuki, en regardant son téléphone.\n\n'
'Pas de réponse de "K".\n\n'
'Le jour du festival arriva. 14h : 200 utilisateurs. 15h : 500 utilisateurs. Les robots se multipliaient automatiquement.\n\n'
'À 16h, le pic d''affluence : **847 utilisateurs simultanés**. L''application ne ralentit même pas.\n\n'
'Kenji s''approcha, les yeux brillants.\n\n'
'"Tu as sauvé le festival," dit-il. "Et... je suis désolé d''avoir douté de toi au début."\n\n'
'Yuki sourit. "Sans ton annonce précipitée, j''aurais jamais découvert l''Auto-Scaling."\n\n'
'Un élève s''approcha, émerveillé. "C''est toi qui as créé l''appli ? C''est génial ! Tu pourrais m''apprendre ?"\n\n'
'Yuki regarda l''application fonctionner parfaitement.\n\n'
'"Je crois que je viens de trouver ma vocation."',
ARRAY['cloudwatch_logs', 'cloudwatch_alarms', 'autoscaling', 'aws_security'], 5, 'chapter'),

(6, 'Épilogue : Architecture de l''App 🏗️', 
E'Voici comment tous les services se connectent :\n\n'
'```\n'
'┌─────────────────────────────────────────────────────────────┐\n'
'│                    L''APPLICATION FESTIVAL                    │\n'
'└─────────────────────────────────────────────────────────────┘\n\n'
'    UTILISATEUR (Élève avec son téléphone)\n'
'              │\n'
'              ▼\n'
'    ┌─────────────────────┐\n'
'    │   PORTE D''ENTRÉE    │  ← API Gateway (contrôle d''accès)\n'
'    │   AVEC GARDIEN      │     Vérifie les Badges (IAM)\n'
'    └──────────┬──────────┘\n'
'               │\n'
'               ▼\n'
'    ┌─────────────────────┐\n'
'    │   ROBOT CUISINIER   │  ← Lambda (s''exécute sur demande)\n'
'    │      (Lambda)       │     Armée de robots (Auto-Scaling)\n'
'    └──────────┬──────────┘\n'
'               │\n'
'       ┌───────┴───────┐\n'
'       │               │\n'
'       ▼               ▼\n'
'┌──────────────┐  ┌──────────────┐\n'
'│  COFFRE-FORT │  │   CASIER     │  ← S3 (stockage fichiers)\n'
'│   NUMÉRIQUE  │  │   INFINI     │\n'
'│(Secrets Mgr) │  │    (S3)      │\n'
'└──────────────┘  └──────────────┘\n'
'       │\n'
'       ▼\n'
'┌──────────────┐\n'
'│   FICHES     │  ← DynamoDB (base de données)\n'
'│  ÉLÈVES      │\n'
'│ (DynamoDB)   │\n'
'└──────┬───────┘\n'
'       │\n'
'       └──────► ┌──────────────┐  ← SQS (file d''attente)\n'
'                │    BOÎTE     │\n'
'                │   AUX LETTRES│\n'
'                └──────────────┘\n'
'                \n'
'                ┌──────────────┐  ← SNS (notifications)\n'
'                │  HAUT-PARLEUR│\n'
'                │    (SNS)     │\n'
'                └──────────────┘\n\n'
'┌─────────────────────────────────────────────────────────────┐\n'
'│              TABLEAU DE BORD DU PROVISEUR                   │\n'
'│                  (CloudWatch + Auto-Scaling)                │\n'
'│   • Surveille les performances                              │\n'
'│   • Déclenche l''armée de robots si besoin                   │\n'
'│   • Détecte les attaques (DDOS)                             │\n'
'└─────────────────────────────────────────────────────────────┘\n'
'```\n\n'
'---\n\n'
'**Concepts clés à retenir :**\n\n'
'| Service AWS | Nom dans l''histoire | Fonction |\n'
'|-------------|---------------------|----------|\n'
'| Lambda | Robot Cuisinier | Exécute du code sur demande |\n'
'| IAM | Badges d''Accès | Gère les permissions |\n'
'| API Gateway | Porte d''Entrée | Contrôle l''accès à l''API |\n'
'| S3 | Casier Infini | Stocke les fichiers |\n'
'| DynamoDB | Fiches Élèves | Base de données rapide |\n'
'| Secrets Manager | Coffre-Fort | Protège les secrets |\n'
'| SQS | Boîte aux Lettres | File d''attente 1-to-1 |\n'
'| SNS | Haut-Parleur | Notifications 1-to-many |\n'
'| CloudWatch | Tableau de Bord | Surveillance |\n'
'| Auto-Scaling | Armée de Robots | Adaptation automatique |',
ARRAY['aws_architecture', 'aws_integration'], 6, 'epilogue');

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_chapters_concept_keys ON chapters USING GIN(concept_keys);